environment:
  SITL_SPEEDUP: 10
  SITL_RATE: 200

cache:
  - "c:\\Users\\appveyor\\.pip-wheelhouse"

install:
  - ps: |
      New-Item -ItemType Directory -Force -Path c:\Users\appveyor\pip\
      @'
      [global]
      find-links = file://c:/Users/appveyor/.pip-wheelhouse

      [wheel]
      wheel-dir = c:/Users/appveyor/.pip-wheelhouse
      '@ | out-file -Encoding ascii -FilePath c:\Users\appveyor\pip\pip.ini

  - cmd: 'SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH%'
  - cmd: 'SET PYTHONUNBUFFERED=1'

  - cmd: 'python -m pip install pip wheel -U'
  - cmd: 'pip install . -UI'
  - cmd: 'pip install -r requirements.txt -UI'

build_script:
  - cmd: 'nosetests -svx dronekit.test.unit'
  - cmd: 'nosetests -svx dronekit.test.sitl'

clone_depth: 10
test: 'off'
